PRAGMA table_list;
PRAGMA table_info(active_trucks);
PRAGMA table_info(audit_log);
PRAGMA table_info(hub_settings);
PRAGMA table_info(ms_bus_connections);
PRAGMA table_info(ms_connections);
PRAGMA table_info(ms_connector_tokens);
PRAGMA table_info(ms_pairings);
PRAGMA table_info(ms_preentry_connections);
PRAGMA table_info(ms_route_history);
PRAGMA table_info(ms_routes);
PRAGMA table_info(truck_history);
PRAGMA table_info(users);
SELECT 'active_trucks' AS table_name, COUNT(*) AS row_count FROM active_trucks;
SELECT 'audit_log' AS table_name, COUNT(*) AS row_count FROM audit_log;
SELECT 'hub_settings' AS table_name, COUNT(*) AS row_count FROM hub_settings;
SELECT 'ms_route_history' AS table_name, COUNT(*) AS row_count FROM ms_route_history;
SELECT 'ms_routes' AS table_name, COUNT(*) AS row_count FROM ms_routes;
SELECT 'truck_history' AS table_name, COUNT(*) AS row_count FROM truck_history;
SELECT 'users' AS table_name, COUNT(*) AS row_count FROM users;
SELECT MAX(synced_at) AS latest_ms_route_sync FROM ms_routes;
SELECT MAX(snapshot_at) AS latest_ms_history_snapshot FROM ms_route_history;
SELECT MAX(action_at) AS latest_truck_history_action FROM truck_history;
