const API=`${location.hostname.endsWith("github.io")?"https://waiting-trucks-report.alert-squid-6738.chatgpt.site":location.origin}/api`,AUTH_KEY="bnak_operator_auth_v2",$=id=>document.getElementById(id),nf=new Intl.NumberFormat("th-TH");let sourceRows=[],filtersReady=false;
const defs=[["attendance","ประเภทงาน",r=>attendance(r),["ปลายทาง","ต้นทาง","จุดดรอป"]],["vehicle","ขนาดรถ",r=>val(r.vehicleType)],["region","ภูมิภาค",r=>val(r.region)],["route","ประเภทเส้นทาง",r=>val(r.routeType||r.routeCategory)],["character","ลักษณะเส้นทาง",r=>val(r.routeCharacteristic||r.characteristic)],["supplier","บริษัทซัพ",r=>val(r.supplierName||r.subcontractorName)]];
document.addEventListener("DOMContentLoaded",()=>{const n=new Date(),s=new Date(n),e=new Date(n);s.setHours(0,0,0,0);e.setHours(23,59,0,0);$("report-from").value=inputDate(s);$("report-to").value=inputDate(e);$("report-load").onclick=load;$("report-export").onclick=exportExcel;buildFilters([])});
function normalizeHub(v){const raw=String(v||"").trim().toUpperCase(),m=raw.match(/([A-Z]{2,6}\d*)_(?:B?HUB)\b/);return m?m[1]:raw}
const pad=n=>String(n).padStart(2,"0"),inputDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`,day=d=>{d=new Date(d);return isNaN(d)?"":`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`},val=v=>String(v||"ไม่ระบุ").trim()||"ไม่ระบุ",esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
async function api(action,params={}){const a=JSON.parse(localStorage.getItem(AUTH_KEY)||"null");if(!a?.token)throw Error("กรุณาเข้าสู่ระบบจากหน้าติดตาม MS ก่อน");const u=new URL(API);u.searchParams.set("action",action);u.searchParams.set("token",a.token);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||"โหลดข้อมูลไม่สำเร็จ");return j.data}
function attendance(r){const v=String(r.attendanceType||"");return v.includes("จุดดร")?"จุดดรอป":v.includes("ปลายทาง")?"ปลายทาง":v.includes("ต้นทาง")?"ต้นทาง":v||"ไม่ระบุ"}function finish(r){return attendance(r)==="ปลายทาง"?(r.completionObservedLive?r.unloadingCompletedAt:""):(r.actualDepartureAt||"")}const vehicle=r=>val(r.vehicleType).toUpperCase();
function dedupeByBarcode(rows){const latest=new Map;for(const r of rows||[]){const key=String(r.proofId||"").trim().toUpperCase();if(!key)continue;const old=latest.get(key),t=Date.parse(r.syncedAt||r.archivedAt||r.sourceUpdatedAt||0),ot=Date.parse(old?.syncedAt||old?.archivedAt||old?.sourceUpdatedAt||0);if(!old||t>=ot)latest.set(key,r)}return [...latest.values()]}
function buildFilters(rows){const old=Object.fromEntries(defs.map(([k])=>[k,new Set([...document.querySelectorAll(`[data-filter-key="${k}"] [data-option]:checked`)].map(x=>x.value))]));$("report-filters").innerHTML=defs.map(([k,label,get,defaults])=>{let opts=defaults||[...new Set(rows.map(get).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"th",{numeric:true}));if(!opts.length)opts=["ไม่ระบุ"];const previous=old[k]||new Set(),hasValidPrevious=opts.some(o=>previous.has(o)),selected=filtersReady&&hasValidPrevious?new Set(opts.filter(o=>previous.has(o))):new Set(opts);return `<details class="multi-filter" data-filter-key="${k}"><summary><span>${esc(label)}</span><strong>ทั้งหมด</strong></summary><div class="multi-menu"><label class="select-all"><input type="checkbox" data-all checked> เลือกทั้งหมด</label>${opts.map(o=>`<label><input type="checkbox" data-option value="${esc(o)}" ${selected.has(o)?"checked":""}> ${esc(o)}</label>`).join("")}</div></details>`}).join("");document.querySelectorAll(".multi-filter").forEach(bind);filtersReady=true}
function bind(box){const all=box.querySelector("[data-all]"),opts=[...box.querySelectorAll("[data-option]")],label=box.querySelector("summary strong"),update=()=>{const n=opts.filter(x=>x.checked).length;all.checked=n===opts.length;all.indeterminate=n>0&&n<opts.length;label.textContent=n===opts.length?"ทั้งหมด":n?`เลือก ${n}`:"ไม่ได้เลือก"};all.onchange=()=>{opts.forEach(x=>x.checked=all.checked);update();render()};opts.forEach(x=>x.onchange=()=>{update();render()});update()}
const selected=k=>new Set([...document.querySelectorAll(`[data-filter-key="${k}"] [data-option]:checked`)].map(x=>x.value)),passes=r=>defs.every(([k,,get])=>selected(k).has(get(r)));
async function load(){const from=new Date($("report-from").value),to=new Date($("report-to").value),branch=normalizeHub($("report-hub").value);if(isNaN(from)||isNaN(to)||to<from)return note("กรุณาเลือกวันและเวลาเริ่มต้น–สิ้นสุดให้ถูกต้อง",true);note("กำลังดึงข้อมูลและตรวจบาร์โค้ดรถ…");$("report-export").disabled=true;try{await api("msRange",{branch,start:day(from),end:day(to)});const result=await api("msArchive",{branch});sourceRows=dedupeByBarcode(result.rows||[]).filter(r=>{const t=new Date(finish(r));return !isNaN(t)&&t>=from&&t<=to});buildFilters(sourceRows);render();$("report-export").disabled=!sourceRows.length}catch(e){note(e.message,true)}}
function render(){const rows=sourceRows.filter(r=>finish(r)&&passes(r));if(!rows.length){$("report-results").innerHTML='<div class="panel empty-state">ไม่พบรถที่จบงานตามช่วงเวลาและตัวกรองที่เลือก</div>';return note("ไม่พบข้อมูลที่ตรงเงื่อนไข")}const map=new Map;rows.forEach(r=>{const d=day(finish(r));if(!map.has(d))map.set(d,[]);map.get(d).push(r)});$("report-results").innerHTML=[...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([d,x])=>renderDay(d,x)).join("");note(`พบ ${nf.format(rows.length)} เที่ยว · แสดงแยก ${nf.format(map.size)} วัน · ไม่รวมยอดข้ามวัน`)}
function renderDay(d,rows){const from=new Date($("report-from").value),to=new Date($("report-to").value),date=new Date(`${d}T00:00:00`),start=day(from)===d?from.getHours():0,end=day(to)===d?to.getHours():23,hours=[];for(let h=start;h<=end;h++)hours.push(h);const groups=new Map;rows.forEach(r=>{const k=`${vehicle(r)}|${attendance(r)}`;if(!groups.has(k))groups.set(k,{car:vehicle(r),type:attendance(r),n:new Map});const h=new Date(finish(r)).getHours(),g=groups.get(k);g.n.set(h,(g.n.get(h)||0)+1)});const body=[...groups.values()].sort((a,b)=>`${a.car}|${a.type}`.localeCompare(`${b.car}|${b.type}`,"th",{numeric:true})).map(g=>{const nums=hours.map(h=>g.n.get(h)||0),total=nums.reduce((a,b)=>a+b,0);return `<tr><th>${esc(g.car)}</th><th>${esc(g.type)}</th>${nums.map(n=>`<td>${n||"-"}</td>`).join("")}<th>${nf.format(total)}</th></tr>`}).join("");return `<section class="panel report-day"><header><div><span>📅 วันที่</span><h2>${date.toLocaleDateString("th-TH")}</h2></div><div><span>ช่วงเวลาที่เลือก</span><strong>${pad(start)}:00–${pad(end)}:59 น.</strong></div><div><span>รถจบงาน</span><strong>${nf.format(rows.length)} เที่ยว</strong></div></header><div class="table-scroll"><table class="daily-report-table"><thead><tr><th>ขนาดรถ</th><th>ประเภทงาน</th>${hours.map(h=>`<th>${pad(h)}:00</th>`).join("")}<th>รวม</th></tr></thead><tbody>${body}</tbody></table></div></section>`}
function exportExcel(){const rows=sourceRows.filter(r=>finish(r)&&passes(r));if(!rows.length)return note("ไม่มีข้อมูลสำหรับ Export",true);const hourly=new Map;for(const r of rows){const at=new Date(finish(r)),k=`${day(at)}|${vehicle(r)}|${attendance(r)}`,g=hourly.get(k)||{date:day(at),vehicle:vehicle(r),attendance:attendance(r),hours:Array(24).fill(0)};g.hours[at.getHours()]++;hourly.set(k,g)}const summary=[...hourly.values()].map(g=>{const x={"วันที่":g.date,"ขนาดรถ":g.vehicle,"ประเภทงาน":g.attendance};g.hours.forEach((n,h)=>x[`${pad(h)}:00`]=n);x["รวม"]=g.hours.reduce((a,b)=>a+b,0);return x}),detail=rows.map(r=>({"บาร์โค้ดรถ":r.proofId,"ชื่อเส้นทาง":r.routeName,"ประเภทงาน":attendance(r),"ขนาดรถ":vehicle(r),"เวลาจบงาน":new Date(finish(r)).toLocaleString("th-TH",{hour12:false}),"บริษัทซัพ":r.supplier||r.subcontractorName||"","ชื่อคนขับ":r.driverName||"","เบอร์โทร":r.driverPhone||""})),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),"สรุปรายชั่วโมง");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(detail),"รายการรถ");XLSX.writeFile(wb,`สรุปรถจบงาน_${normalizeHub($("report-hub").value)}_${day(new Date($("report-from").value))}_${day(new Date($("report-to").value))}.xlsx`)}
function note(m,e=false){$("report-note").textContent=m;$("report-note").classList.toggle("form-error",e)}
