const API = `${window.location.hostname.endsWith("github.io") ? "https://waiting-trucks-report.alert-squid-6738.chatgpt.site" : window.location.origin}/api`;
const AUTH_KEY = "bnak_operator_auth_v2", $ = (id) => document.getElementById(id), nf = new Intl.NumberFormat("th-TH");
let trips = [], loading = false;
document.addEventListener("DOMContentLoaded", () => {
  $("scan-day").value = localDay(new Date()); $("scan-refresh").onclick = loadTrips; $("scan-search-btn").onclick = loadTrips; $("scan-search").oninput = renderTrips; $("scan-day").onchange = loadTrips; $("parcel-detail-close").onclick = () => $("parcel-detail-dialog").close();
  document.addEventListener("click", (event) => { const button = event.target.closest("[data-parcel-type]"); if (button) openDetails(button.dataset.proof, button.dataset.parcelType); });
  loadTrips(); setInterval(() => document.visibilityState === "visible" && loadTrips(true), 3000);
});
function localDay(date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function esc(value) { return String(value ?? "").replace(/[&<>"']/g, (x) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x])); }
function auth() { try { return JSON.parse(localStorage.getItem(AUTH_KEY) || "null"); } catch { return null; } }
async function apiGet(action, params = {}) { const session = auth(); if (!session?.token) throw new Error("กรุณาเข้าสู่ระบบจากหน้าติดตามรถ MS ก่อน"); const url = new URL(API); url.searchParams.set("action",action); url.searchParams.set("token",session.token); Object.entries(params).forEach(([key,value]) => url.searchParams.set(key,value)); const response = await fetch(url,{cache:"no-store"}), json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.message || "โหลดข้อมูลไม่สำเร็จ"); return json.data; }
async function loadTrips(silent=false) { if (loading) return; loading=true; if (!silent) $("scan-status").textContent="กำลังโหลดข้อมูลจาก MS…"; try { const result=await apiGet("preEntryTrips",{branch:$("scan-hub").value.trim().toUpperCase(),day:$("scan-day").value}); trips=result.trips||[]; $("scan-expected").textContent=nf.format(result.expected||0); $("scan-entered").textContent=nf.format(result.entered||0); $("scan-pending").textContent=nf.format(result.pending||0); $("scan-status").textContent=`อัปเดตล่าสุด ${new Date(result.updatedAt).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})} น. · อัปเดตอัตโนมัติทุก 3 วินาที`; $("scan-live").textContent=`${result.hub} · ข้อมูลวันที่ ${result.day}`; renderTrips(); } catch(error) { $("scan-status").textContent=error.message; $("scan-empty").textContent=error.message; $("scan-empty").classList.remove("hidden"); } finally { loading=false; } }
function renderTrips() { const query=$("scan-search").value.trim().toLowerCase(), rows=trips.filter((row)=>!query||`${row.proofId} ${row.routeName}`.toLowerCase().includes(query)); if(!rows.length){$("scan-empty").textContent=trips.length?"ไม่พบข้อมูลตามคำค้นหา":"ไม่พบพัสดุของวันที่เลือก";$("scan-empty").classList.remove("hidden");$("scan-table-wrap").classList.add("hidden");return;} $("scan-body").innerHTML=rows.map((row)=>`<tr><td><strong>${esc(row.proofId)}</strong><small>${esc(row.routeName)}</small></td><td>${esc(row.previousHub||"-")}</td><td>${esc(row.targetHub||"-")}</td>${countCell(row,"total","expected")}${countCell(row,"already","entered")}${countCell(row,"no_entry","pending")}</tr>`).join("");$("scan-empty").classList.add("hidden");$("scan-table-wrap").classList.remove("hidden"); }
function countCell(row,type,key){const value=Number(row[key])||0;return `<td><button type="button" class="scan-count ${type}" data-proof="${esc(row.proofId)}" data-parcel-type="${type}" ${value?"":"disabled"}>${nf.format(value)}</button></td>`;}
async function openDetails(proofId,type){const labels={total:"พัสดุที่ควรเข้าทั้งหมด",already:"พัสดุที่เข้าคลังแล้ว",no_entry:"พัสดุที่ยังไม่เข้า"};$("parcel-detail-kind").textContent=labels[type];$("parcel-detail-title").textContent=proofId;$("parcel-detail-count").textContent="กำลังโหลด…";$("parcel-detail-body").innerHTML='<tr><td colspan="6">กำลังโหลดข้อมูล…</td></tr>';$("parcel-detail-dialog").showModal();try{const result=await apiGet("pendingParcels",{branch:$("scan-hub").value.trim().toUpperCase(),proofId,day:$("scan-day").value,type}),rows=result.parcels||[];$("parcel-detail-count").textContent=`${result.routeName||""} · ${nf.format(result.total||rows.length)} ชิ้น`;$("parcel-detail-body").innerHTML=rows.length?rows.map((row)=>`<tr><td><strong>${esc(row.pno)}</strong></td><td>${esc(row.backingNo||"-")}</td><td>${esc(row.lastAction||row.status||"-")}</td><td>${esc(row.lastActionAt||"-")}</td><td>${esc(row.targetHub||"-")}</td><td>${esc(row.targetBranch||"-")}</td></tr>`).join(""):'<tr><td colspan="6">ไม่พบรายการพัสดุ</td></tr>';}catch(error){$("parcel-detail-count").textContent="โหลดไม่สำเร็จ";$("parcel-detail-body").innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;}}
