const API=`${location.hostname.endsWith("github.io")?"https://waiting-trucks-report.alert-squid-6738.chatgpt.site":location.origin}/api`,AUTH_KEY="bnak_operator_auth_v2",$=id=>document.getElementById(id),nf=new Intl.NumberFormat("th-TH");let trips=[],detailRows=[],detailInfo={},loading=false;
document.addEventListener("DOMContentLoaded",()=>{$("scan-day").value=day(new Date);$("scan-refresh").onclick=load;$("scan-search-btn").onclick=load;$("scan-search").oninput=render;$("scan-day").onchange=load;$("scan-export").onclick=exportMain;$("parcel-detail-export").onclick=exportDetail;$("parcel-detail-close").onclick=()=>$("parcel-detail-dialog").close();document.addEventListener("click",e=>{const b=e.target.closest("[data-parcel-type]");if(b)details(b.dataset.proof,b.dataset.parcelType)});load();setInterval(()=>document.visibilityState==="visible"&&load(true),3000)});
function normalizeHub(v){const raw=String(v||"").trim().toUpperCase(),m=raw.match(/([A-Z]{2,6}\d*)_(?:B?HUB)\b/);return m?m[1]:raw}
const day=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
async function api(action,params={}){let a;try{a=JSON.parse(localStorage.getItem(AUTH_KEY)||"null")}catch{}if(!a?.token)throw Error("กรุณาเข้าสู่ระบบจากหน้าติดตามรถ MS ก่อน");const u=new URL(API);u.searchParams.set("action",action);u.searchParams.set("token",a.token);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||"โหลดข้อมูลไม่สำเร็จ");return j.data}
async function load(silent=false){if(loading)return;loading=true;if(!silent)$("scan-status").textContent="กำลังโหลดข้อมูลจาก MS…";try{const x=await api("preEntryTrips",{branch:normalizeHub($("scan-hub").value),day:$("scan-day").value});trips=x.trips||[];$("scan-expected").textContent=nf.format(x.expected||0);$("scan-entered").textContent=nf.format(x.entered||0);$("scan-pending").textContent=nf.format(x.pending||0);$("scan-status").textContent=`อัปเดตล่าสุด ${new Date(x.updatedAt).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})} น. · อัตโนมัติทุก 3 วินาที`;$("scan-live").textContent=`${x.hub} · วันที่ ${x.day}`;render()}catch(e){$("scan-status").textContent=e.message;$("scan-empty").textContent=e.message;$("scan-empty").classList.remove("hidden")}finally{loading=false}}
function visibleTrips(){const q=$("scan-search").value.trim().toLowerCase();return trips.filter(r=>Number(r.pending)>0).filter(r=>!q||`${r.proofId} ${r.routeName} ${r.previousHub} ${r.targetHub} ${r.supplier} ${r.driverName} ${r.driverPhone}`.toLowerCase().includes(q))}
function render(){const rows=visibleTrips();if(!rows.length){$("scan-empty").textContent=trips.length?"ไม่มีเที่ยวรถที่ยังมีพัสดุไม่เข้าคลัง":"ไม่พบข้อมูลของวันที่เลือก";$("scan-empty").classList.remove("hidden");$("scan-table-wrap").classList.add("hidden");return}$("scan-body").innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.proofId)}</strong><small>${esc(r.routeName)}</small><small>ซัพ: ${esc(r.supplier||"-")}</small><small>คนขับ: ${esc(r.driverName||"-")}${r.driverPhone?` · ${esc(r.driverPhone)}`:""}</small></td><td>${esc(r.previousHub||"-")}</td><td>${esc(r.targetHub||"-")}</td>${cell(r,"total","expected")}${cell(r,"already","entered")}${cell(r,"no_entry","pending")}</tr>`).join("");$("scan-empty").classList.add("hidden");$("scan-table-wrap").classList.remove("hidden")}
function cell(r,type,key){const n=Number(r[key])||0;return `<td><button type="button" class="scan-count ${type}" data-proof="${esc(r.proofId)}" data-parcel-type="${type}" ${n?"":"disabled"}>${nf.format(n)}</button></td>`}
async function details(proof,type){const names={total:"พัสดุที่ควรเข้าทั้งหมด",already:"พัสดุที่เข้าคลังแล้ว",no_entry:"พัสดุที่ยังไม่เข้า"};detailRows=[];detailInfo={proof,type,label:names[type]};$("parcel-detail-kind").textContent=names[type];$("parcel-detail-title").textContent=proof;$("parcel-detail-count").textContent="กำลังโหลด…";$("parcel-detail-body").innerHTML='<tr><td colspan="4">กำลังโหลดข้อมูล…</td></tr>';$("parcel-detail-dialog").showModal();try{const x=await api("pendingParcels",{branch:normalizeHub($("scan-hub").value),proofId:proof,day:$("scan-day").value,type});detailRows=x.parcels||[];detailInfo={...detailInfo,routeName:x.routeName||""};$("parcel-detail-count").textContent=`${x.routeName||""} · ${nf.format(x.total||detailRows.length)} ชิ้น`;$("parcel-detail-body").innerHTML=detailRows.length?detailRows.map((r,i)=>`<tr><td>${nf.format(i+1)}</td><td><strong>${esc(r.pno)}</strong><small>แบ็กกิ้ง: ${esc(r.backingNo||"-")}</small></td><td><strong>${esc(r.lastAction||r.status||"-")}</strong><small>${esc(r.lastActionAt||"-")}</small></td><td><strong>${esc(r.targetHub||"-")}</strong><small>${esc(r.targetBranch||"-")}</small></td></tr>`).join(""):'<tr><td colspan="4">ไม่พบรายการพัสดุ</td></tr>'}catch(e){$("parcel-detail-count").textContent="โหลดไม่สำเร็จ";$("parcel-detail-body").innerHTML=`<tr><td colspan="4">${esc(e.message)}</td></tr>`}}
function exportMain(){const rows=visibleTrips().map(r=>({"บาร์โค้ดรถ":r.proofId,"ชื่อเส้นทาง":r.routeName,"HUB ต้นทาง":r.previousHub,"HUB ปลายทาง":r.targetHub,"บริษัทซัพ":r.supplier||"","ชื่อคนขับ":r.driverName||"","เบอร์โทร":r.driverPhone||"","พัสดุที่ควรเข้า":Number(r.expected)||0,"พัสดุที่เข้าคลังแล้ว":Number(r.entered)||0,"พัสดุที่ยังไม่เข้า":Number(r.pending)||0}));exportRows(rows,`พัสดุยังไม่เข้าคลัง_${$("scan-day").value}`)}
function exportDetail(){const rows=detailRows.map((r,i)=>({"ลำดับ":i+1,"เลขพัสดุ":r.pno,"เลขแบ็กกิ้ง":r.backingNo||"","การดำเนินการล่าสุด":r.lastAction||r.status||"","เวลาที่ดำเนินการล่าสุด":r.lastActionAt||"","HUB ปลายทาง":r.targetHub||"","สาขาปลายทาง":r.targetBranch||""}));exportRows(rows,`${detailInfo.label||"พัสดุ"}_${detailInfo.proof||""}_${$("scan-day").value}`)}
function exportRows(rows,name){if(!rows.length)return alert("ไม่มีข้อมูลสำหรับ Export");if(window.XLSX){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"ข้อมูล");XLSX.writeFile(wb,`${name}.xlsx`);return}const keys=Object.keys(rows[0]),csv="\ufeff"+[keys,...rows.map(r=>keys.map(k=>`"${String(r[k]??"").replaceAll('"','""')}"`))].map(x=>x.join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`${name}.csv`;a.click();URL.revokeObjectURL(a.href)}
