const API=`${location.hostname.endsWith("github.io")?"https://waiting-trucks-report.alert-squid-6738.chatgpt.site":location.origin}/api`,AUTH_KEY="bnak_operator_auth_v2",$=id=>document.getElementById(id),nf=new Intl.NumberFormat("th-TH");let trips=[],loading=false;
document.addEventListener("DOMContentLoaded",()=>{$("scan-day").value=day(new Date);$("scan-refresh").onclick=load;$("scan-search-btn").onclick=load;$("scan-search").oninput=render;$("scan-day").onchange=load;$("parcel-detail-close").onclick=()=>$("parcel-detail-dialog").close();document.addEventListener("click",e=>{const b=e.target.closest("[data-parcel-type]");if(b)details(b.dataset.proof,b.dataset.parcelType)});load();setInterval(()=>document.visibilityState==="visible"&&load(true),3000)});
function normalizeHub(v){const raw=String(v||"").trim().toUpperCase(),m=raw.match(/([A-Z]{2,6}\d*)_(?:B?HUB)\b/);return m?m[1]:raw}
const day=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,esc=v=>String(v??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
async function api(action,params={}){let a;try{a=JSON.parse(localStorage.getItem(AUTH_KEY)||"null")}catch{}if(!a?.token)throw Error("กรุณาเข้าสู่ระบบจากหน้าติดตามรถ MS ก่อน");const u=new URL(API);u.searchParams.set("action",action);u.searchParams.set("token",a.token);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.message||"โหลดข้อมูลไม่สำเร็จ");return j.data}
async function load(silent=false){if(loading)return;loading=true;if(!silent)$("scan-status").textContent="กำลังโหลดข้อมูลจาก MS…";try{const x=await api("preEntryTrips",{branch:normalizeHub($("scan-hub").value),day:$("scan-day").value});trips=x.trips||[];$("scan-expected").textContent=nf.format(x.expected||0);$("scan-entered").textContent=nf.format(x.entered||0);$("scan-pending").textContent=nf.format(x.pending||0);$("scan-status").textContent=`อัปเดตล่าสุด ${new Date(x.updatedAt).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})} น. · อัตโนมัติทุก 3 วินาที`;$("scan-live").textContent=`${x.hub} · วันที่ ${x.day}`;render()}catch(e){$("scan-status").textContent=e.message;$("scan-empty").textContent=e.message;$("scan-empty").classList.remove("hidden")}finally{loading=false}}
function render(){const q=$("scan-search").value.trim().toLowerCase(),rows=trips.filter(r=>!q||`${r.proofId} ${r.routeName}`.toLowerCase().includes(q));if(!rows.length){$("scan-empty").textContent=trips.length?"ไม่พบข้อมูลตามคำค้นหา":"ไม่พบพัสดุของวันที่เลือก";$("scan-empty").classList.remove("hidden");$("scan-table-wrap").classList.add("hidden");return}$("scan-body").innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.proofId)}</strong><small>${esc(r.routeName)}</small></td><td>${esc(r.previousHub||"-")}</td><td>${esc(r.targetHub||"-")}</td>${cell(r,"total","expected")}${cell(r,"already","entered")}${cell(r,"no_entry","pending")}</tr>`).join("");$("scan-empty").classList.add("hidden");$("scan-table-wrap").classList.remove("hidden")}
function cell(r,type,key){const n=Number(r[key])||0;return `<td><button type="button" class="scan-count ${type}" data-proof="${esc(r.proofId)}" data-parcel-type="${type}" ${n?"":"disabled"}>${nf.format(n)}</button></td>`}
async function details(proof,type){const names={total:"พัสดุที่ควรเข้าทั้งหมด",already:"พัสดุที่เข้าคลังแล้ว",no_entry:"พัสดุที่ยังไม่เข้า"};$("parcel-detail-kind").textContent=names[type];$("parcel-detail-title").textContent=proof;$("parcel-detail-count").textContent="กำลังโหลด…";$("parcel-detail-body").innerHTML='<tr><td colspan="6">กำลังโหลดข้อมูล…</td></tr>';$("parcel-detail-dialog").showModal();try{const x=await api("pendingParcels",{branch:normalizeHub($("scan-hub").value),proofId:proof,day:$("scan-day").value,type}),rows=x.parcels||[];$("parcel-detail-count").textContent=`${x.routeName||""} · ${nf.format(x.total||rows.length)} ชิ้น`;$("parcel-detail-body").innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.pno)}</strong></td><td>${esc(r.backingNo||"-")}</td><td>${esc(r.lastAction||r.status||"-")}</td><td>${esc(r.lastActionAt||"-")}</td><td>${esc(r.targetHub||"-")}</td><td>${esc(r.targetBranch||"-")}</td></tr>`).join(""):'<tr><td colspan="6">ไม่พบรายการพัสดุ</td></tr>'}catch(e){$("parcel-detail-count").textContent="โหลดไม่สำเร็จ";$("parcel-detail-body").innerHTML=`<tr><td colspan="6">${esc(e.message)}</td></tr>`}}
