import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("../../",import.meta.url);const f=await Promise.all(["ms.js","style.css","sw.js"].map(p=>readFile(new URL(p,root),"utf8")));const front=f[0],style=f[1],sw=f[2];
test("owner-approved Classic lower source is integrated",()=>{const v=style.split("MS_LOWER_CLASSIC_V12")[1]||"";assert.ok(v);assert.match(v,/type-badge\.inbound\{background:#ffd400;color:#111/);assert.match(v,/type-badge\.outbound\{background:#202124;color:#fff/);assert.match(v,/type-badge\.drop\{background:#1978ba;color:#fff/);assert.doesNotMatch(v,/\.metric-card|\.ms-metrics/);assert.match(front,/function isPhoneDesktopSiteLayout/);assert.match(front,/function completedTodayOvertimeRows/)});
test("legacy and canonical redesign generations cannot compete with Classic",()=>{assert.equal((style.match(/MS_LOWER_CLASSIC_V12/g)||[]).length,1);for(const legacy of ["MS_LOWER_CANONICAL_V11","MS_LOWER_VISUAL_ACCEPTANCE_V3","MS_OPERATION_PRESENTATION_V4","MS_PRESENTATION_STATE_CORRECTION_V5","MS_LOWER_REFERENCE_V7"])assert.doesNotMatch(style,new RegExp(legacy));assert.doesNotMatch(front,/operationTimeline\(/);assert.doesNotMatch(front,/class="lower-operation/);assert.match(front,/class="classic-operation/)});
test("route overtime truth",()=>{assert.match(front,/const arrival = parseDate\(row\.actualArrivalAt\)/);assert.match(front,/overStandard: isDestination\(row\) && completed[\s\S]*slaMinutes > standard/);assert.match(front,/state\.status === "unload-overtime" && isCompletedTodayOvertime\(row\)/)});
test("completed-today hydration is coalesced without changing realtime cadence",()=>{assert.match(front,/pollMs:\s*4000/);assert.equal((front.match(/apiGet\("msCompletedToday"/g)||[]).length,1);assert.match(front,/completedTodayLoadPromise\?\.key === key/);assert.match(front,/completedTodayRetryAt = Date\.now\(\) \+ 60_000/);assert.match(front,/completed-today detail hydrates only when the lightweight daily total changes/)});
test("SW freshness only",()=>{assert.match(sw,/cache: "no-store"/);assert.doesNotMatch(sw,/MS_JS_HOTFIX|MS_CSS_HOTFIX|String\.raw|appendPatch|MS_OWNER_CORRECTION/) });
