import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import test from "node:test";
import { stageFrontend } from "./stage-dev-runtime.mjs";
const root=new URL("../../",import.meta.url);
const files=await Promise.all(["ms.js","style.css","ms.html","sw.js"].map(p=>readFile(new URL(p,root),"utf8")));
const rawFront=files[0],front=stageFrontend(rawFront),style=files[1],html=files[2],sw=files[3];
const between=(text,a,b)=>{const x=text.indexOf(a),y=text.indexOf(b,x+a.length);assert.ok(x>=0&&y>x,"missing block "+a);return text.slice(x,y)};
const visual=style.split("MS_LOWER_CLASSIC_V12")[1]||"";
function loadTiming(){const src=between(front,"function unloadTiming","function isCompletedUnloadOverStandard");const ctx={Date,state:{standards:{"6W":45}},parseDate(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d},normalizeVehicle(){return "6W"},unloadStandard(){return 45},isDestination(){return true},confirmedEffectiveArrival(row){const route=this.parseDate(row.actualArrivalAt);if(!route)return null;return [row.actualArrivalAt,row.scheduleKitArrivalAt,row.scheduleTbrArrivalAt].map(v=>this.parseDate(v)).filter(Boolean).sort((a,b)=>a-b)[0]||null}};vm.createContext(ctx);vm.runInContext(src+";globalThis.fn=unloadTiming",ctx);return ctx.fn}
test("frozen upper metric markup and eight standalone classic lower cards",()=>{assert.equal((html.match(/class="metric-card/g)||[]).length,8);const r=between(front,"function renderFilterSummary(rows)","async function applyMetricFilter");assert.equal((r.match(/class="summary-card/g)||[]).length,8);assert.equal((r.match(/data-summary-status=/g)||[]).length,8);for(const key of ["all","waiting","unloading","completed","unload-overtime","origin","drop","cancelled"])assert.match(r,new RegExp(`data-summary-status="${key}"`));assert.doesNotMatch(r,/data-summary-substatus|summary-subfilter/);assert.match(r,/completedTodayOvertimeRows\(\)\.length/);assert.match(r,/queue\.cancelled && isCancelledToday\(row\)/)});
test("classic black yellow presentation is one lower visual generation",()=>{assert.equal((style.match(/MS_LOWER_CLASSIC_V12/g)||[]).length,1);assert.doesNotMatch(style,/MS_LOWER_CANONICAL_V11/);assert.match(visual,/grid-template-columns:repeat\(8,minmax\(0,1fr\)\)/);assert.match(visual,/button\.is-active\{[^}]*background:#fff8d6/);assert.match(visual,/type-badge\.inbound\{background:#ffd400;color:#111/);assert.match(visual,/type-badge\.outbound\{background:#202124;color:#fff/);assert.match(visual,/type-badge\.drop\{background:#1978ba;color:#fff/);assert.doesNotMatch(visual,/\.metric-card|\.ms-metrics|data-metric/)});
test("arrival display requires Route confirmation then uses earliest Route KIT TBR",()=>{const schedule=between(front,"function scheduleSection(row, mode)","function queueInfo");assert.match(schedule,/\? confirmedEffectiveArrival\(row\)/);const src=between(front,"function effectiveArrival(row)","function attendanceLabel(row)");const ctx={parseDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}};vm.createContext(ctx);vm.runInContext(src+";globalThis.fn=confirmedEffectiveArrival",ctx);assert.equal(ctx.fn({actualArrivalAt:"2026-09-09T09:09:00Z",scheduleKitArrivalAt:"2026-09-09T09:09:00Z",scheduleTbrArrivalAt:"2026-09-09T08:10:00Z"}).toISOString(),"2026-09-09T08:10:00.000Z");assert.equal(ctx.fn({scheduleKitArrivalAt:"2026-09-09T09:09:00Z",scheduleTbrArrivalAt:"2026-09-09T08:10:00Z"}),null)});
test("main arrival source detail hides Route but preserves confirmed effective truth",()=>{const sources=between(front,"function arrivalSources(row)","function arrivalSourceDateTime(value)");assert.doesNotMatch(sources,/<em>Route<\/em>/);assert.match(sources,/<em>KIT<\/em>/);assert.match(sources,/<em>TBR<\/em>/);assert.match(sources,/<em>ถึงจริงที่ใช้<\/em>/);assert.match(sources,/const effective = confirmedEffectiveArrival\(row\)/);assert.doesNotMatch(sources,/const earliest = \[row\.scheduleKitArrivalAt/)});
test("SLA Route uses earliest confirmed arrival while S E remains work duration",()=>{const fn=loadTiming();const t=fn({unloadingState:2,actualArrivalAt:"2026-09-08T15:56:00Z",scheduleKitArrivalAt:"2026-09-08T15:40:00Z",scheduleTbrArrivalAt:"2026-09-08T15:50:00Z",scheduleUnloadingStartedAt:"2026-09-08T18:01:00Z",unloadingCompletedAt:"2026-09-08T18:47:00Z"},new Date("2026-09-08T18:47:00Z"));assert.equal(t.slaMinutes,187);assert.equal(t.workMinutes,46);assert.equal(t.standard,45);assert.equal(t.overStandard,true);assert.equal(t.slaMinutes-t.standard,142)});
test("active current SLA excluded from completed overtime",()=>{const t=loadTiming()({unloadingState:1,actualArrivalAt:"2026-09-08T17:40:00Z",scheduleKitArrivalAt:"2026-09-08T17:35:00Z",scheduleUnloadingStartedAt:"2026-09-08T17:50:00Z"},new Date("2026-09-08T18:40:00Z"));assert.equal(t.slaMinutes,65);assert.equal(t.overStandard,false);assert.match(front,/function isCompletedTodayOvertime/)});
test("overtime still shares completed-today authority",()=>{assert.match(front,/function isCompletedTodayOvertime/);assert.match(front,/function completedTodayOvertimeRows/);assert.match(front,/state\.status === "unload-overtime" && isCompletedTodayOvertime\(row\)/);assert.equal((front.match(/apiGet\("msCompletedToday"/g)||[]).length,1)});
test("completed detail transient zero and cancelled count use read-only daily facts",()=>{assert.match(front,/completedTodayZeroProbedKey/);assert.match(front,/state\.completedToday === 0 && completedTodayZeroProbedKey !== zeroProbeKey/);assert.match(front,/void loadCompletedTodayRows\(true\)/);assert.match(front,/apiGet\("msCancelledToday"/);assert.match(front,/MS_LOWER_DAILY_COUNTS_MIDNIGHT_V2/);assert.doesNotMatch(front,/MS_LOWER_DAILY_COUNTS_0700_V1|lowerOperatingDayValue/);assert.match(front,/if \(expected === 0\)\s*return completedTodayHydratedKey === completedTodayDatasetKey\(\)/);assert.match(front,/if \(expected === 0\) return false/);assert.match(front,/setInterval\(\(\) => state\.auth && loadData\(true\), CONFIG\.pollMs\)/);assert.match(front,/pollMs:\s*4000/)});
test("status cell is compact ordered facts not full-cell operation card",()=>{const table=between(front,"function tableRow(row)","function card(row)");const card=between(front,"function card(row)","let cancelRouteTarget");assert.match(front,/function renderOperation\(row\)/);assert.match(front,/classic-operation-row/);assert.match(table,/operationHtml/);assert.match(card,/renderOperation\(row\)/);assert.doesNotMatch(front,/class="lower-operation/);assert.doesNotMatch(front,/operationTimeline\(/)});
test("unload presentation separates S-E work time from earliest-arrival SLA truth",()=>{const operation=between(front,"function renderOperation(row)","// LOCAL_ROUTE_BARCODE_V1");assert.doesNotMatch(front,/function displayedUnloadTiming\(row/);assert.match(operation,/classicOperationRow\("ใช้เวลาลงรถจริง", timing\.workMinutes/);assert.match(operation,/classicOperationRow\("SLA Route", timing\.slaMinutes/);assert.match(operation,/shortDateTime\(confirmedEffectiveArrival\(row\)\)/);assert.match(front,/const arrival = confirmedEffectiveArrival\(row\)/);assert.match(front,/เวลาถึงที่เร็วที่สุด/);assert.match(front,/overStandard: isDestination\(row\) && completed/)});
test("work type labels are exact and mobile includes a non-duplicate subtitle",()=>{const labels=between(front,"function attendanceLabel(row)","function punctuality(row)");for(const text of ["ปลายทาง","ต้นทาง","จุดดรอป","รถเข้าคลัง","รถออกคลัง","ลงของและเดินทางต่อ"])assert.match(labels,new RegExp(text));assert.doesNotMatch(labels,/เข้า ·|ออก ·|ผ่าน ·/);const card=between(front,"function card(row)","let cancelRouteTarget");assert.match(card,/compact-work-type[\s\S]*type-badge[\s\S]*attendanceLabel\(row\)/)});
test("barcode keeps integer geometry and has no runtime CSS injection",()=>{assert.match(front,/shape-rendering="crispEdges"/);assert.match(front,/width="\$\{total\}" height="\$\{barHeight \+ labelHeight\}"/);assert.doesNotMatch(front,/installLocalBarcodeStyle/);assert.match(visual,/local-barcode-panel[^}]*overflow-x:auto/);assert.match(visual,/local-barcode-svg[^}]*max-width:none!important/)});
test("barcode control is balanced and table hover is light gray",()=>{assert.match(visual,/local-route-barcode[^}]*align-items:center/);assert.match(visual,/local-barcode-toggle[^}]*align-self:center/);assert.match(visual,/ms-table tbody tr:hover td\{background:#f1f3f4\}/);assert.doesNotMatch(visual,/ms-table tbody tr:hover td\{background:#fffbed\}/)});
test("operation summaries use semantic danger safe and drop emphasis",()=>{assert.match(front,/classicOperationSummary/);assert.match(visual,/classic-operation-summary\.is-danger[^}]*background:#fff0ef/);assert.match(visual,/classic-operation-summary\.is-safe[^}]*background:#eef8f2/);assert.match(visual,/classic-operation-summary\.is-drop[^}]*background:#eef7fc/)});
test("phone desktop site contract remains unchanged",()=>{const src=between(front,"function isPhoneDesktopSiteLayout(","function renderRowsProgressively(rows)");const ctx={};vm.createContext(ctx);vm.runInContext(src+";globalThis.desktop=isPhoneDesktopSiteLayout;globalThis.mobile=useMobileCardLayout",ctx);for(const w of [375,390,412,430])assert.equal(ctx.mobile(w,w,800),true);for(const w of [768,820,1024])assert.equal(ctx.mobile(w,w,1200),true);for(const w of [980,1024]){assert.equal(ctx.desktop(w,390,844),true);assert.equal(ctx.mobile(w,390,844),false)}for(const w of [1280,1366,1440,1920])assert.equal(ctx.mobile(w,390,844),false);assert.doesNotMatch(src,/userAgent|Android|iPhone|Samsung/i);assert.match(visual,/html\.ms-desktop-site-phone \.ms-page #desktop-table\{display:block/)});
test("service worker freshness only with classic release",()=>{assert.match(sw,/20260909-06-classic-arrival-truth/);assert.match(sw,/cache: "no-store"/);assert.doesNotMatch(sw,/MS_JS_HOTFIX|MS_CSS_HOTFIX|String\.raw|appendPatch|style\.textContent/)});
// OWNER_CLASSIC_LOWER_DEPLOY_GATE_V13
