import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import test from "node:test";
const root=new URL("../../",import.meta.url);
const files=await Promise.all(["ms.js","style.css","ms.html","sw.js"].map(p=>readFile(new URL(p,root),"utf8")));
const front=files[0],style=files[1],html=files[2],sw=files[3];
const between=(text,a,b)=>{const x=text.indexOf(a),y=text.indexOf(b,x+a.length);assert.ok(x>=0&&y>x,"missing block "+a);return text.slice(x,y)};
const visual=style.split("MS_LOWER_CLASSIC_V12")[1]||"";
function loadTiming(){const src=between(front,"function unloadTiming","function isCompletedUnloadOverStandard");const ctx={Date,state:{standards:{"6W":45}},parseDate(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d},normalizeVehicle(){return "6W"},unloadStandard(){return 45},isDestination(){return true}};vm.createContext(ctx);vm.runInContext(src+";globalThis.fn=unloadTiming",ctx);return ctx.fn}
test("frozen upper metric markup and classic six lower cards",()=>{assert.equal((html.match(/class="metric-card/g)||[]).length,8);const r=between(front,"function renderFilterSummary(rows)","async function applyMetricFilter");assert.equal((r.match(/data-summary-status=/g)||[]).length,6);for(const key of ["all","waiting","unloading","completed","origin","drop"])assert.match(r,new RegExp(`data-summary-status="${key}"`));assert.doesNotMatch(r,/data-summary-status="(?:unload-overtime|cancelled)"/)});
test("classic black yellow presentation is one lower visual generation",()=>{assert.equal((style.match(/MS_LOWER_CLASSIC_V12/g)||[]).length,1);assert.doesNotMatch(style,/MS_LOWER_CANONICAL_V11/);assert.match(visual,/grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/);assert.match(visual,/button\.is-active\{[^}]*background:#fff8d6/);assert.match(visual,/type-badge\.inbound\{background:#ffd400;color:#111/);assert.match(visual,/type-badge\.outbound\{background:#202124;color:#fff/);assert.match(visual,/type-badge\.drop\{background:#1978ba;color:#fff/);assert.doesNotMatch(visual,/\.metric-card|\.ms-metrics|data-metric/)});
test("arrival display requires Route confirmation then uses earliest Route KIT TBR",()=>{const schedule=between(front,"function scheduleSection(row, mode)","function queueInfo");assert.match(schedule,/\? confirmedEffectiveArrival\(row\)/);const src=between(front,"function effectiveArrival(row)","function attendanceLabel(row)");const ctx={parseDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}};vm.createContext(ctx);vm.runInContext(src+";globalThis.fn=confirmedEffectiveArrival",ctx);assert.equal(ctx.fn({actualArrivalAt:"2026-09-09T09:09:00Z",scheduleKitArrivalAt:"2026-09-09T09:09:00Z",scheduleTbrArrivalAt:"2026-09-09T08:10:00Z"}).toISOString(),"2026-09-09T08:10:00.000Z");assert.equal(ctx.fn({scheduleKitArrivalAt:"2026-09-09T09:09:00Z",scheduleTbrArrivalAt:"2026-09-09T08:10:00Z"}),null)});
test("arrival source detail preserves Route KIT TBR and confirmed effective time",()=>{const sources=between(front,"function arrivalSources(row)","function arrivalSourceDateTime(value)");assert.match(sources,/<em>Route<\/em>/);assert.match(sources,/<em>KIT<\/em>/);assert.match(sources,/<em>TBR<\/em>/);assert.match(sources,/<em>ใช้เวลา<\/em>/);assert.match(sources,/const effective = confirmedEffectiveArrival\(row\)/);assert.doesNotMatch(sources,/const earliest = \[row\.scheduleKitArrivalAt/)});
test("171 45 gives 126 and S E is 46",()=>{const t=loadTiming()({unloadingState:2,actualArrivalAt:"2026-09-08T15:56:00Z",scheduleUnloadingStartedAt:"2026-09-08T18:01:00Z",unloadingCompletedAt:"2026-09-08T18:47:00Z"},new Date("2026-09-08T18:47:00Z"));assert.equal(t.slaMinutes,171);assert.equal(t.workMinutes,46);assert.equal(t.standard,45);assert.equal(t.overStandard,true);assert.equal(t.slaMinutes-t.standard,126)});
test("active current SLA excluded from completed overtime",()=>{const t=loadTiming()({unloadingState:1,actualArrivalAt:"2026-09-08T17:40:00Z",scheduleUnloadingStartedAt:"2026-09-08T17:50:00Z"},new Date("2026-09-08T18:40:00Z"));assert.equal(t.slaMinutes,60);assert.equal(t.overStandard,false);assert.match(front,/function isCompletedTodayOvertime/)});
test("overtime still shares completed-today authority",()=>{assert.match(front,/function isCompletedTodayOvertime/);assert.match(front,/function completedTodayOvertimeRows/);assert.match(front,/state\.status === "unload-overtime" && isCompletedTodayOvertime\(row\)/);assert.equal((front.match(/apiGet\("msCompletedToday"/g)||[]).length,1)});
test("completed detail and transient zero use read-only detail without extra polling",()=>{assert.match(front,/completedTodayZeroProbedKey/);assert.match(front,/state\.completedToday === 0 && completedTodayZeroProbedKey !== zeroProbeKey/);assert.match(front,/void loadCompletedTodayRows\(true\)/);assert.match(front,/if \(expected === 0\)\s*return completedTodayHydratedKey === completedTodayDatasetKey\(\)/);assert.match(front,/if \(expected === 0\) return false/);assert.match(front,/setInterval\(\(\) => state\.auth && loadData\(true\), CONFIG\.pollMs\)/);assert.match(front,/pollMs:\s*4000/)});
test("status cell is compact ordered facts not full-cell operation card",()=>{const table=between(front,"function tableRow(row)","function card(row)");const card=between(front,"function card(row)","let cancelRouteTarget");assert.match(front,/function renderOperation\(row\)/);assert.match(front,/classic-operation-row/);assert.match(table,/operationHtml/);assert.match(card,/renderOperation\(row\)/);assert.doesNotMatch(front,/class="lower-operation/);assert.doesNotMatch(front,/operationTimeline\(/)});
test("work type is compact and mobile moves it into header",()=>{assert.match(front,/function attendanceWorkLabel/);assert.match(front,/เข้า · ปลายทาง/);assert.match(front,/ออก · ต้นทาง/);assert.match(front,/ผ่าน · จุดดรอป/);const card=between(front,"function card(row)","let cancelRouteTarget");assert.match(card,/compact-card-tags[\s\S]*type-badge/);assert.doesNotMatch(card,/compact-attendance/)});
test("barcode keeps integer geometry and has no runtime CSS injection",()=>{assert.match(front,/shape-rendering="crispEdges"/);assert.match(front,/width="\$\{total\}" height="\$\{barHeight \+ labelHeight\}"/);assert.doesNotMatch(front,/installLocalBarcodeStyle/);assert.match(visual,/local-barcode-panel[^}]*overflow-x:auto/);assert.match(visual,/local-barcode-svg[^}]*max-width:none!important/)});
test("phone desktop site contract remains unchanged",()=>{const src=between(front,"function isPhoneDesktopSiteLayout(","function renderRowsProgressively(rows)");const ctx={};vm.createContext(ctx);vm.runInContext(src+";globalThis.desktop=isPhoneDesktopSiteLayout;globalThis.mobile=useMobileCardLayout",ctx);for(const w of [375,390,412,430])assert.equal(ctx.mobile(w,w,800),true);for(const w of [768,820,1024])assert.equal(ctx.mobile(w,w,1200),true);for(const w of [980,1024]){assert.equal(ctx.desktop(w,390,844),true);assert.equal(ctx.mobile(w,390,844),false)}for(const w of [1280,1366,1440,1920])assert.equal(ctx.mobile(w,390,844),false);assert.doesNotMatch(src,/userAgent|Android|iPhone|Samsung/i);assert.match(visual,/html\.ms-desktop-site-phone \.ms-page #desktop-table\{display:block/)});
test("service worker freshness only with classic release",()=>{assert.match(sw,/20260909-06-classic-arrival-truth/);assert.match(sw,/cache: "no-store"/);assert.doesNotMatch(sw,/MS_JS_HOTFIX|MS_CSS_HOTFIX|String\.raw|appendPatch|style\.textContent/)});
// OWNER_CLASSIC_LOWER_DEPLOY_GATE_V12
