const SETTINGS={SPREADSHEET_ID:'1sqON2-nJLYCS26wWihFmOw27bmg_BdpuRab3maSr1ng',ACTIVE_SHEET:'ระบบ_รถรอลงงาน',HISTORY_SHEET:'ระบบ_ประวัติ',AUDIT_SHEET:'ระบบ_บันทึกการใช้งาน'};
const ACTIVE_HEADERS=['id','barcode','previousStation','routeName','driverName','driverPhone','vehicleType','plate','parcels','arrivalAt','hub','supplier','importedAt','sourceFile'];
const HISTORY_HEADERS=[...ACTIVE_HEADERS,'status','actionAt','note'],AUDIT_HEADERS=['timestamp','action','recordId','detail'];
function setupSystem(operatorPin){if(!operatorPin||String(operatorPin).length<4)throw new Error('รหัสต้องมีอย่างน้อย 4 ตัว');PropertiesService.getScriptProperties().setProperty('OPERATOR_PIN_HASH',hash_(String(operatorPin)));const ss=SpreadsheetApp.openById(SETTINGS.SPREADSHEET_ID);ensureSheet_(ss,SETTINGS.ACTIVE_SHEET,ACTIVE_HEADERS);ensureSheet_(ss,SETTINGS.HISTORY_SHEET,HISTORY_HEADERS);ensureSheet_(ss,SETTINGS.AUDIT_SHEET,AUDIT_HEADERS);return 'ตั้งค่าระบบสำเร็จ'}
function doGet(e){try{const a=String(e.parameter.action||'list');if(a==='verify'){assertPin_(e.parameter.pin);return json_({ok:true,data:true})}if(a==='history')return json_({ok:true,data:readSheet_(SETTINGS.HISTORY_SHEET).slice(-1000)});if(a==='health')return json_({ok:true,data:{service:'waiting-trucks-api',time:new Date().toISOString()}});return json_({ok:true,data:readSheet_(SETTINGS.ACTIVE_SHEET)})}catch(error){return json_({ok:false,message:error.message,code:error.code||'SERVER_ERROR'})}}
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(20000);const b=JSON.parse(e.postData.contents||'{}');assertPin_(b.pin);if(b.action==='import')return json_({ok:true,data:importRows_(b.rows||[],b.fileName||'')});if(b.action==='complete')return json_({ok:true,data:archiveRecord_(b.id,'COMPLETED',b.note||'')});if(b.action==='remove')return json_({ok:true,data:archiveRecord_(b.id,'REMOVED',b.note||'')});throw new Error('ไม่รู้จักคำสั่งที่ส่งมา')}catch(error){return json_({ok:false,message:error.message,code:error.code||'SERVER_ERROR'})}finally{if(lock.hasLock())lock.releaseLock()}}
function importRows_(incoming,fileName){const ss=SpreadsheetApp.openById(SETTINGS.SPREADSHEET_ID),active=ensureSheet_(ss,SETTINGS.ACTIVE_SHEET,ACTIVE_HEADERS),blocked=new Set(readSheet_(SETTINGS.HISTORY_SHEET).map(r=>r.id)),map=new Map(readSheet_(SETTINGS.ACTIVE_SHEET).map(r=>[r.id,r]));let imported=0,skipped=0;incoming.forEach(raw=>{const row=cleanIncoming_(raw,fileName);if(!row.previousStation||!row.arrivalAt)return;if(blocked.has(row.id)){skipped++;return}map.set(row.id,row);imported++});replaceData_(active,ACTIVE_HEADERS,[...map.values()]);audit_('IMPORT','',`${fileName}: ${imported} imported, ${skipped} skipped`);return{imported,skipped,total:map.size}}
function archiveRecord_(id,status,note){if(!id)throw new Error('ไม่พบรหัสรายการ');const ss=SpreadsheetApp.openById(SETTINGS.SPREADSHEET_ID),active=ensureSheet_(ss,SETTINGS.ACTIVE_SHEET,ACTIVE_HEADERS),rows=readSheet_(SETTINGS.ACTIVE_SHEET),i=rows.findIndex(r=>String(r.id)===String(id));if(i<0)throw new Error('รายการนี้ถูกดำเนินการไปแล้ว กรุณารีเฟรชหน้าเว็บ');appendObject_(ensureSheet_(ss,SETTINGS.HISTORY_SHEET,HISTORY_HEADERS),HISTORY_HEADERS,{...rows[i],status,actionAt:new Date().toISOString(),note:String(note).slice(0,500)});active.deleteRow(i+2);audit_(status,id,note);return{id,status}}
function cleanIncoming_(r,file){const d=new Date(r.arrivalAt),barcode=String(r.barcode||'').trim(),natural=barcode||[r.plate,r.routeName,isNaN(d)?r.arrivalAt:d.toISOString()].join('|');return{id:hash_(natural),barcode,previousStation:String(r.previousStation||'').trim(),routeName:String(r.routeName||'').trim(),driverName:String(r.driverName||'').trim(),driverPhone:String(r.driverPhone||'').trim(),vehicleType:String(r.vehicleType||'').trim(),plate:String(r.plate||'').trim(),parcels:Number(r.parcels)||0,arrivalAt:isNaN(d)?String(r.arrivalAt||''):d.toISOString(),hub:String(r.hub||'').trim(),supplier:String(r.supplier||'').trim(),importedAt:new Date().toISOString(),sourceFile:String(file).slice(0,200)}}
function assertPin_(pin){const saved=PropertiesService.getScriptProperties().getProperty('OPERATOR_PIN_HASH');if(!saved)throw new Error('ยังไม่ได้ตั้งค่ารหัส ให้รัน setupSystem ก่อน');if(hash_(String(pin||''))!==saved){const e=new Error('รหัสจัดการไม่ถูกต้อง');e.code='INVALID_PIN';throw e}}
function hash_(v){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v)).replace(/=+$/,'')}function ensureSheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.getRange(1,1,1,h.length).setValues([h]).setFontWeight('bold').setBackground('#101828').setFontColor('#fff');s.setFrozenRows(1)}return s}function readSheet_(n){const ss=SpreadsheetApp.openById(SETTINGS.SPREADSHEET_ID),h=n===SETTINGS.ACTIVE_SHEET?ACTIVE_HEADERS:n===SETTINGS.HISTORY_SHEET?HISTORY_HEADERS:AUDIT_HEADERS,s=ensureSheet_(ss,n,h);if(s.getLastRow()<2)return[];const v=s.getDataRange().getValues(),heads=v.shift().map(String);return v.filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>Object.fromEntries(heads.map((x,i)=>[x,r[i]instanceof Date?r[i].toISOString():r[i]])))}function replaceData_(s,h,rows){if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).clearContent();if(rows.length)s.getRange(2,1,rows.length,h.length).setValues(rows.map(r=>h.map(x=>r[x]??'')))}function appendObject_(s,h,o){s.appendRow(h.map(x=>o[x]??''))}function audit_(a,id,d){const ss=SpreadsheetApp.openById(SETTINGS.SPREADSHEET_ID);appendObject_(ensureSheet_(ss,SETTINGS.AUDIT_SHEET,AUDIT_HEADERS),AUDIT_HEADERS,{timestamp:new Date().toISOString(),action:a,recordId:id,detail:String(d||'').slice(0,500)})}function json_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}
