import {
  integer,
  primaryKey,
  real,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
export const users = sqliteTable("users", {
  username: text("username").primaryKey(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull(),
  branches: text("branches").notNull().default(""),
  active: integer("active").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
});
export const activeTrucks = sqliteTable("active_trucks", {
  id: text("id").primaryKey(),
  barcode: text("barcode"),
  previousStation: text("previous_station"),
  routeName: text("route_name"),
  driverName: text("driver_name"),
  driverPhone: text("driver_phone"),
  vehicleType: text("vehicle_type"),
  plate: text("plate"),
  parcels: integer("parcels").notNull().default(0),
  arrivalAt: text("arrival_at").notNull(),
  hub: text("hub").notNull(),
  supplier: text("supplier"),
  importedAt: text("imported_at"),
  sourceFile: text("source_file"),
  workStatus: text("work_status"),
  startedAt: text("started_at"),
  startedBy: text("started_by"),
});
export const truckHistory = sqliteTable("truck_history", {
  historyId: text("history_id").primaryKey(),
  id: text("id").notNull(),
  barcode: text("barcode"),
  previousStation: text("previous_station"),
  routeName: text("route_name"),
  driverName: text("driver_name"),
  driverPhone: text("driver_phone"),
  vehicleType: text("vehicle_type"),
  plate: text("plate"),
  parcels: integer("parcels").notNull().default(0),
  arrivalAt: text("arrival_at").notNull(),
  hub: text("hub").notNull(),
  supplier: text("supplier"),
  importedAt: text("imported_at"),
  sourceFile: text("source_file"),
  workStatus: text("work_status"),
  startedAt: text("started_at"),
  startedBy: text("started_by"),
  status: text("status").notNull(),
  actionAt: text("action_at").notNull(),
  note: text("note"),
  operator: text("operator").notNull(),
});
export const hubSettings = sqliteTable(
  "hub_settings",
  {
    branch: text("branch").notNull(),
    category: text("category").notNull(),
    settingKey: text("setting_key").notNull(),
    label: text("label"),
    startHour: real("start_hour"),
    endHour: real("end_hour"),
    minutes: integer("minutes"),
    enabled: integer("enabled").notNull().default(1),
    updatedAt: text("updated_at").notNull(),
    updatedBy: text("updated_by").notNull(),
  },
  (t) => [primaryKey({ columns: [t.branch, t.category, t.settingKey] })],
);
export const msRoutes = sqliteTable("ms_routes", {
  id: text("id").primaryKey(),
  hub: text("hub").notNull(),
  proofId: text("proof_id"),
  routeName: text("route_name"),
  region: text("region"),
  routeAttribute: text("route_attribute"),
  routeType: text("route_type"),
  attendanceType: text("attendance_type"),
  estimatedArrivalAt: text("estimated_arrival_at"),
  actualArrivalAt: text("actual_arrival_at"),
  estimatedDepartureAt: text("estimated_departure_at"),
  actualDepartureAt: text("actual_departure_at"),
  supplier: text("supplier"),
  vehicleType: text("vehicle_type"),
  plate: text("plate"),
  driverName: text("driver_name"),
  driverPhone: text("driver_phone"),
  trackingStatus: text("tracking_status"),
  vehicleStatus: text("vehicle_status"),
  loadStatus: text("load_status"),
  unloadingState: integer("unloading_state"),
  unloadingCompletedAt: text("unloading_completed_at"),
  sourceUpdatedAt: text("source_updated_at"),
  expectedParcels: integer("expected_parcels"),
  enteredParcels: integer("entered_parcels"),
  pendingParcels: integer("pending_parcels"),
  scheduleKitArrivalAt: text("schedule_kit_arrival_at"),
  scheduleTbrArrivalAt: text("schedule_tbr_arrival_at"),
  arrivedParcels: integer("arrived_parcels"),
  arrivedBags: integer("arrived_bags"),
  syncedAt: text("synced_at").notNull(),
  syncedBy: text("synced_by").notNull(),
});
export const msRouteHistory = sqliteTable("ms_route_history", {
  historyId: text("history_id").primaryKey(),
  routeId: text("route_id").notNull(),
  hub: text("hub").notNull(),
  eventType: text("event_type").notNull(),
  snapshotAt: text("snapshot_at").notNull(),
  payloadJson: text("payload_json").notNull(),
  syncedBy: text("synced_by").notNull(),
});
export const msConnections = sqliteTable("ms_connections", {
  hub: text("hub").primaryKey(),
  sessionCipher: text("session_cipher").notNull(),
  deviceCipher: text("device_cipher").notNull(),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
  lastSuccessAt: text("last_success_at"),
  lastError: text("last_error"),
});
export const msPreEntryConnections = sqliteTable("ms_preentry_connections", {
  hub: text("hub").primaryKey(),
  credentialsCipher: text("credentials_cipher").notNull(),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
  lastSuccessAt: text("last_success_at"),
  lastError: text("last_error"),
});
export const msBusConnections = sqliteTable("ms_bus_connections", {
  hub: text("hub").primaryKey(),
  credentialsCipher: text("credentials_cipher").notNull(),
  updatedAt: text("updated_at").notNull(),
  updatedBy: text("updated_by").notNull(),
  lastSuccessAt: text("last_success_at"),
  lastError: text("last_error"),
});
export const auditLog = sqliteTable("audit_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  timestamp: text("timestamp").notNull(),
  action: text("action").notNull(),
  recordId: text("record_id"),
  detail: text("detail"),
  operator: text("operator").notNull(),
});
